#!/usr/bin/env python3

import mujoco
import mujoco_ros

import matplotlib.pyplot as plt
import numpy as np
from copy import deepcopy
from pathlib import Path
import os
import rospkg
import rospy
import argparse

from IPython import embed


def run():
    print(f"Mujoco version: {mujoco.__version__}")

    mj_env = mujoco_ros.MujocoEnv(
        None,
        start_ros_core=False,
        unpause=False,
        headless=True,
    )

    embed()
    mj_env.attach_viewer(active=True)


if __name__ == "__main__":
    run()
