MujocoPlugins:
  - type: mujoco_ros_hog/MujocoHogPlugin
    hogBodies:
      hogBox:
        desiredPose:
         - 0.0   # X
         - 1.0   # Y
         - 1.0 # Z
         - 1.0   # qw
         - 0.0   # qx
         - 0.0   # qy
         - 0.0   # qz