<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mujoco_ros_control</name>
  <version>1.0.0</version>
  <description>ros_control and ros2_control integration for mujoco_ros</description>

  <url type="repository">https://github.com/DavidPL1/mujoco_ros_pkgs</url>
  <url type="bugtracker">https://github.com/DavidPL1/mujoco_ros_pkgs/issues</url>

  <maintainer email="dleins@techfak.uni-bielefeld.de">David P. Leins</maintainer>
  <author>David P. Leins</author>

  <license>BSD</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake_python</buildtool_depend>

  <depend>controller_manager</depend>
  <depend>hardware_interface</depend>
  <depend>mujoco_ros</depend>
  <depend>py_binding_tools</depend>
  <depend condition="$ROS_VERSION == 1">pybind11_catkin</depend>
  <depend condition="$ROS_VERSION == 2">pybind11_vendor</depend>
  <depend>pluginlib</depend>

  <depend condition="$ROS_VERSION == 1">angles</depend>
  <depend condition="$ROS_VERSION == 1">controller_interface</depend>
  <depend condition="$ROS_VERSION == 1">control_toolbox</depend>
  <depend condition="$ROS_VERSION == 1">joint_limits_interface</depend>
  <depend condition="$ROS_VERSION == 1">roscpp</depend>
  <depend condition="$ROS_VERSION == 1">transmission_interface</depend>
  <depend condition="$ROS_VERSION == 1">urdf</depend>

  <depend condition="$ROS_VERSION == 2">rclcpp</depend>
  <depend condition="$ROS_VERSION == 2">rclcpp_lifecycle</depend>
  <depend condition="$ROS_VERSION == 2">lifecycle_msgs</depend>

  <exec_depend condition="$ROS_VERSION == 2">joint_state_broadcaster</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">joint_state_publisher</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">forward_command_controller</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">robot_state_publisher</exec_depend>
  <exec_depend condition="$ROS_VERSION == 2">xacro</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">effort_controllers</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">joint_state_controller</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">position_controllers</exec_depend>
  <exec_depend condition="$ROS_VERSION == 1">velocity_controllers</exec_depend>

  <test_depend condition="$ROS_VERSION == 2">ament_cmake_gtest</test_depend>
  <test_depend condition="$ROS_VERSION == 1">rostest</test_depend>
  <test_depend>mujoco_ros_testing_utils</test_depend>

  <export>
    <mujoco_ros condition="$ROS_VERSION == 1" plugin="${prefix}/mujoco_ros_control_plugin.xml" />
    <mujoco_ros_control condition="$ROS_VERSION == 1" plugin="${prefix}/default_mujoco_ros_robot_hw_sim_plugin.xml" />
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
